# Generated by Django 2.2.7 on 2019-12-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191203_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='year',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
